project_id = "jpdrwnuvtqvbdjbzvwah"

[functions.admin-list-users]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = false

[functions.auto-billing]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
